- .npmrc
- package.json
- packages/walletkit-ui/.eslintrc
- packages/walletkit-ui/package.json
- packages/walletkit-ui/src/index.ts
- packages/walletkit-ui/src/store/block.ts
- packages/walletkit-ui/src/store/block.unit.ts
- packages/walletkit-ui/src/store/index.ts
- packages/walletkit-ui/src/store/ocean.ts
- packages/walletkit-ui/src/store/ocean.unit.ts
- packages/walletkit-ui/src/store/transaction_queue.ts
- packages/walletkit-ui/src/store/transaction_queue.unit.ts
- pnpm-lock.yaml
> feature(store): added block, ocean and transaction_queue store

- packages/walletkit-core/src/api/index.ts
- packages/walletkit-core/src/api/whale.ts
- packages/walletkit-core/src/api/whale.unit.ts
- packages/walletkit-ui/src/contexts/WhaleContext.tsx
- packages/walletkit-ui/src/contexts/index.ts
> feature(setup): add WhaleContext inside walletkit-ui

- packages/walletkit-ui/package.json
- packages/walletkit-ui/src/contexts/WhaleContext.test.tsx
- packages/walletkit-ui/src/contexts/__snapshots__/WhaleContext.test.tsx.snap
- pnpm-lock.yaml
> chore(test): add ui test for whale context provider

- package.json
- packages/walletkit-core/package.json
- packages/walletkit-ui/package.json
- packages/walletkit-ui/src/store/block.ts
- packages/walletkit-ui/tsconfig.build.json
- pnpm-lock.yaml
- tsconfig.base.json
> feature(store): update to es2019

- packages/walletkit-ui/package.json
- packages/walletkit-ui/src/contexts/ThemeProvider.test.tsx
- packages/walletkit-ui/src/contexts/ThemeProvider.tsx
- packages/walletkit-ui/src/contexts/__snapshots__/ThemeProvider.test.tsx.snap
- packages/walletkit-ui/src/contexts/index.ts
- pnpm-lock.yaml
Add `ThemeProvider` context and testing
Fixes #
> feature(context): move ThemeProvider inside walletkit-ui

- packages/walletkit-core/src/api/index.ts
- packages/walletkit-core/src/api/paginatedAPI.ts
- packages/walletkit-core/src/api/paginatedAPI.unit.ts
- packages/walletkit-ui/src/store/index.ts
- packages/walletkit-ui/src/store/wallet.ts
- packages/walletkit-ui/src/store/wallet.unit.ts
- packages/walletkit-ui/src/store/website.ts
> feature(walletkit-ui): move `website` and `wallet` store

- packages/walletkit-core/src/api/whale.ts
- packages/walletkit-core/src/api/whale.unit.ts
- packages/walletkit-ui/src/contexts/StoreServiceProvider.tsx
- packages/walletkit-ui/src/contexts/index.ts
> feature(context): move StoreServiceProvider inside walletkit-ui

- packages/walletkit-core/src/api/addressValidator.ts
- packages/walletkit-core/src/api/addressValidator.unit.ts
- packages/walletkit-core/src/api/index.ts
> feature(api): add address validator inside walletkit-core

- packages/walletkit-core/src/api/index.ts
- packages/walletkit-core/src/api/playground.ts
- packages/walletkit-ui/src/contexts/PlaygroundContext.tsx
- packages/walletkit-ui/src/contexts/index.ts
> feature(walletkit-ui): setup playground context

- packages/walletkit-ui/package.json
- packages/walletkit-ui/src/contexts/LanguageProvider.test.tsx
- packages/walletkit-ui/src/contexts/LanguageProvider.tsx
- packages/walletkit-ui/src/contexts/__snapshots__/LanguageProvider.test.tsx.snap
- pnpm-lock.yaml
As titled
Fixes https://github.com/WavesHQ/walletkit/issues/17
> feature(walletkit-ui): add language context

- packages/walletkit-ui/src/contexts/index.ts
> feature(walletkit-ui): export language provider

- packages/walletkit-ui/src/contexts/LanguageProvider.test.tsx
> chore(test): unskip language provider test

- packages/walletkit-ui/src/store/wallet.ts
I need DexPricesProps for one of the Desktop light wallet components
Fixes #
> feature(wallet-kit-store): add export DexPricesProps

- packages/walletkit-ui/src/contexts/WalletNodeProvider.tsx
- packages/walletkit-ui/src/contexts/WalletPersistenceContext.tsx
- packages/walletkit-ui/src/contexts/index.ts
> feature(walletkit-ui): WalletNodeProvider and WalletPersistenceProvider

- packages/walletkit-ui/src/contexts/StoreProvider.tsx
> feature(walletkit-ui): StoreProvider

- packages/walletkit-ui/src/contexts/DisplayBalanceContext.tsx
- packages/walletkit-ui/src/contexts/index.ts
> feature(walletkit-ui): add DisplayBalanceContext

- packages/walletkit-core/src/website/website.ts
New feature flag for OCG 
Fixes #
> feature(core): add ocg feature flag

- .github/workflows/ci.yml
- package.json
- packages/walletkit-ui/package.json
- pnpm-lock.yaml
> chore(deps): bump packages

- packages/walletkit-core/src/api/environment.ts
- packages/walletkit-core/src/api/whale.ts
- packages/walletkit-core/src/api/whale.unit.ts
- packages/walletkit-ui/src/contexts/DeFiScanContext.tsx
- packages/walletkit-ui/src/contexts/WhaleContext.test.tsx
- packages/walletkit-ui/src/contexts/__snapshots__/WhaleContext.test.tsx.snap
> feature(devnet): support for devnet

- packages/walletkit-core/src/api/whale.ts
- packages/walletkit-core/src/api/whale.unit.ts
- packages/walletkit-ui/src/contexts/WhaleContext.test.tsx
- packages/walletkit-ui/src/contexts/__snapshots__/WhaleContext.test.tsx.snap
> chore(deps): update devnet link

- package.json
- packages/walletkit-core/package.json
- packages/walletkit-core/src/api/whale.ts
- packages/walletkit-core/src/api/whale.unit.ts
- packages/walletkit-ui/package.json
- packages/walletkit-ui/src/contexts/WhaleContext.test.tsx
- packages/walletkit-ui/src/contexts/__snapshots__/WhaleContext.test.tsx.snap
- pnpm-lock.yaml
> feature(scan): updated link

- .npmrc
- package.json
- packages/walletkit-core/src/index.ts
- packages/walletkit-core/src/testcontainers/DeFiChainStubContainer.ts
- packages/walletkit-core/src/testcontainers/index.ts
- pnpm-lock.yaml
https://github.com/WavesHQ/bridge/pull/297
Allows to do unit/integration testing via Jest. Runs three containers at the same time.
Fixes #
> feature(testcontainers): DeFiChainStubContainer

- packages/walletkit-ui/src/store/auctions.ts
- packages/walletkit-ui/src/store/auctions.unit.ts
- packages/walletkit-ui/src/store/index.ts
As titled
Fixes #
https://github.com/WavesHQ/walletkit/issues/22
> feat(walletkit-ui): add auctions to store

- packages/walletkit-ui/src/store/futureSwap.ts
- packages/walletkit-ui/src/store/futureSwap.unit.ts
- packages/walletkit-ui/src/store/index.ts
As titled
Fixes #
https://github.com/WavesHQ/walletkit/issues/24
> feat(walletkit-ui): add futureSwaps to store

- packages/walletkit-core/src/api/whale.ts
- packages/walletkit-core/src/api/whale.unit.ts
- packages/walletkit-ui/src/contexts/WhaleContext.test.tsx
- packages/walletkit-ui/src/contexts/__snapshots__/WhaleContext.test.tsx.snap
> chore(devnet): remove port number

- package.json
- packages/walletkit-ui/package.json
- pnpm-lock.yaml
> chore(ops): bump updates

- packages/walletkit-bot/package.json
- packages/walletkit-bot/src/api/DeFiChainCore.ts
- packages/walletkit-bot/src/api/RefundBot.ts
- pnpm-lock.yaml
> chore(walletkit-bot): remove src from walletkit-core import

- .github/workflows/ci.yml
- .github/workflows/release.yml
- package.json
- packages/walletkit-bot/package.json
- packages/walletkit-core/package.json
- packages/walletkit-testcontainers/package.json
- packages/walletkit-ui/package.json
- pnpm-lock.yaml
> chore(ops): update deps

- packages/walletkit-bot/package.json
- packages/walletkit-bot/src/api/StateRelayerBot.ts
- packages/walletkit-bot/src/api/StateRelayerBot.unit.ts
- packages/walletkit-bot/src/api/index.ts
- packages/walletkit-bot/src/utils/oceanMockedData.ts
- pnpm-lock.yaml
Create StateRelayer bot to read data from Ocean and update SC
> feat(bot): Add StateRelayer bot

- package.json
- packages/walletkit-bot/package.json
- packages/walletkit-bot/src/api/RefundBot.unit.ts
- packages/walletkit-core/package.json
- packages/walletkit-core/src/api/address.ts
- packages/walletkit-testcontainers/package.json
- packages/walletkit-ui/package.json
- pnpm-lock.yaml
> feature(viem): update deps

- package.json
- packages/walletkit-bot/package.json
- packages/walletkit-core/package.json
- packages/walletkit-testcontainers/package.json
- packages/walletkit-ui/package.json
- pnpm-lock.yaml
> chore(ops): update walletkit

- packages/walletkit-core/src/api/whale.ts
- packages/walletkit-core/src/api/whale.unit.ts
- packages/walletkit-ui/src/contexts/WhaleContext.test.tsx
- packages/walletkit-ui/src/contexts/__snapshots__/WhaleContext.test.tsx.snap
> chore(ops): update changi network to https

- packages/walletkit-core/src/api/network.ts
> chore(ops): use the new changi network in jellyfish

- packages/walletkit-core/src/website/website.ts
> chore(core): add feature flag - evm

- packages/walletkit-core/src/website/website.ts
> feature(walletkit-ui): add flag Id for loop dusd

- packages/walletkit-ui/src/store/transaction_queue.ts
> refactor(lint): added null as a return type for DfTxSigner

- packages/walletkit-core/src/website/website.ts
> feature(walletkit-core): add flag id for save tx
